# SONiC chosen Configuration file for the usbmount package

# disable usbmount
ENABLED=0

# 8 usbmount points available
MOUNTPOINTS="/media/usb0 /media/usb1 /media/usb2 /media/usb3
             /media/usb4 /media/usb5 /media/usb6 /media/usb7"

# Supported Filesystem types
FILESYSTEMS="vfat ext2 ext3 ext4"

# Allows 180 seconds for a usbmount add operation to be complete
USBMOUNT_LOCK_RETRIES=9

# Enable debug level logging
VERBOSE=yes

# Don't use sync option as sync is performed before reboot or during
# umount
MOUNTOPTIONS="noexec,nodev,noatime,nodiratime"
