include /etc/radsecproxy.conf.d/common*.conf

client 127.0.0.0/8 {
        type udp
        secret sonicradsec
}

include /etc/radsecproxy.conf.d/tls-*.conf

include /etc/radsecproxy.conf.d/server-*.conf

include /etc/radsecproxy.conf.d/realm-*.conf

