# Use lookup tables for interface name translation
lookup_table(name="baseport_alias_map" file="/var/lib/rsyslog/rsyslog_baseport_aliases.json" reloadOnHup="off")
lookup_table(name="port_alias_map" file="/var/lib/rsyslog/rsyslog_port_aliases.json" reloadOnHup="on")

# Reload "port_alias_map" lookup table if we get a special message "port-alias-reload: <reason>"
# # from rsyslog-config daemon
if $programname == "rsyslog-config.py" and $!msg1 startswith " port-alias-reload:" then {
  reload_lookup_table("port_alias_map", "none")
}

# Change interface name alias displayed
# Exempt message severities at or below DEBUG(7) and from certain senders
if not ($syslogseverity >= 7 or $programname startswith ["mgmt-framework#"]) then {
  set $.idx = re_extract($!msg1,"(Ethernet|Eth)([[:digit:]]+) *[[][[:digit:],/ ]+[]]",0,2,"none");
  if ($.idx != "none") then {
    set $.port_alias = lookup("baseport_alias_map","" & $.idx & "[");
    if ($.port_alias != "none") then {
      set $.master = re_extract($!msg1,"((Ethernet|Eth)([[:digit:]]+) *[[])[[:digit:],/ ]+[]]",0,1,"none");
      if ($.master != "none") then {
        set $!msg1 = replace($!msg1,$.master,$.port_alias & " [");
        set $.port_alias = lookup("baseport_alias_map","" & $.idx);
        if ($.port_alias != "none") then {
          set $!msg1 = replace($!msg1,"Ethernet" & $.idx,$.port_alias);
          set $!msg1 = replace($!msg1,"Eth" & $.idx & ".",$.port_alias & ".");
        }
        set $.idx = "ok";
      }
    }
  } else {
    set $.idx = re_extract($!msg1,"(Ethernet|Eth|Po)([[:digit:]]+)",0,2,"none");
    if ($.idx != "none") then {
      set $!msg1 = replace($!msg1,"Po" & $.idx & ".","PortChannel" & $.idx & ".");
      set $.port_alias = lookup("port_alias_map",$.idx);
      if ($.port_alias != "none") then {
        set $!msg1 = replace($!msg1,"Ethernet" & $.idx,$.port_alias);
        set $!msg1 = replace($!msg1,"Eth" & $.idx & ".",$.port_alias & ".");
        set $.idx = "ok";
      }
    }
  }
  if ($.idx == "ok") then {
    set $.idx = re_extract($!msg1,"Ethernet([[:digit:]]+)",0,1,"none");
    if ($.idx != "none") then {
      set $.port_alias = lookup("port_alias_map",$.idx);
      if ($.port_alias != "none") then {
        set $!msg1 = replace($!msg1,"Ethernet" & $.idx,$.port_alias);
        set $!msg1 = replace($!msg1,"Eth" & $.idx & ".",$.port_alias & ".");
      }
    }else {
     set $.idx = re_extract($!msg1,"(Eth|Po)([[:digit:]]+)[(.)]([[:digit:]]+)",0,2,"none");
     if ($.idx != "none") then {
      set $!msg1 = replace($!msg1,"Po" & $.idx & ".","PortChannel" & $.idx & ".");
      set $.port_alias = lookup("port_alias_map",$.idx);
      if ($.port_alias != "none") then {
        set $!msg1 = replace($!msg1,"Ethernet" & $.idx,$.port_alias);
        set $!msg1 = replace($!msg1,"Eth" & $.idx & ".",$.port_alias & ".");
      }
    }
   }
  }
}
