# Use lookup tables for interface name translation
if not ($syslogseverity >= 7 or $programname startswith ["mgmt-framework#"]) then {
  set $.idx = re_extract($!msg1,"(Eth|Po)([[:digit:]]+)[(.)]([[:digit:]]+)",0,2,"none");
  if($.idx != "none") then
  {
    set $!msg1 = replace($!msg1,"Eth" & $.idx,"Ethernet" & $.idx);
    set $!msg1 = replace($!msg1,"Po" & $.idx,"PortChannel" & $.idx);
    set $.idx = "ok";
  }

  if ($.idx == "ok") then
  {
    set $.idx = re_extract($!msg1,"(Eth|Po)([[:digit:]]+)[(.)]([[:digit:]]+)",0,2,"none");
    if($.idx != "none") then
    {
      set $!msg1 = replace($!msg1,"Eth" & $.idx,"Ethernet" & $.idx);
      set $!msg1 = replace($!msg1,"Po" & $.idx,"PortChannel" & $.idx);
    }
  }
}
