ntp-config.service
ntp.service
ntpconfd.service
warmboot-finalizer.service
watchdog-control.service
rsyslog-config.service
interfaces-config.service
aaastatsd.service
hostname-config.service
updategraph.service
config-setup.service
config-chassisdb.service
ccd.service
resrcmgrd.service
platform-init.service
platform-ready.service
database.service
database@.service
database-chassis.service
eventd.service
bgp@.service
iccpd.service
l2mcd.service
lldp.service
lldp@.service
mfa.service
nat.service
pmon.service
radv.service
sflow.service
snmp.service
mgmt-framework.service
stp.service
tam.service
teamd@.service
telemetry.service
timesync.service
udld.service
vrrp.service
gbsyncd.service
swss.service
swss@.service
syncd@.service
dhcp_relay.service
telemetry.timer
mgmt-framework.timer
