#!/bin/sh

#
# Helper service for the NTP Configuration Daemon (ntpconfd). It takes over
# the role of the original ntp init script/service. The replaced ntp
# script/service now only calls ntpconfd script/service to perform any
# service status changes requested of ntpd.
#
# Here is the call sequence hierarchy:
#
#     ntp --> ntpconfd --> ntp-daemon
#

### BEGIN INIT INFO
# Provides:        ntp-daemon
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start: 
# Default-Stop: 
# Short-Description: NTP daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/sbin/ntpd
PIDFILE=/var/run/ntpd.pid

test -x $DAEMON || exit 5

if [ -r /etc/default/ntp ]; then
	. /etc/default/ntp
fi

#
# ntpconfd takes care of picking up the DHCP version of the configuration
# file and picking out the servers from it.
# Uncomment the next line when ntpconfd begins writing to that file
NTPD_OPTS="$NTPD_OPTS -c /var/run/ntpconfd/etc/ntp.conf"

#
# ntpconfd sets the <vrfName>.vrf file if ntpd has to be started in <vrfName> VRF
#
VRF=""
vrf_log_msg="in default VRF"

# Specify the path where the .vrf files are located
vrf_path="/var/run/ntpconfd/etc/"

# Find the first .vrf file in the specified path
vrf_file=$(find "$vrf_path" -maxdepth 1 -type f -name '*.vrf' -print -quit)

# Check if a .vrf file exists
if [ -n "$vrf_file" ]; then
    # Extract the vrfName from the file name
    vrf_name=$(basename "$vrf_file" .vrf)

    # Assign VRF
    VRF="ip vrf exec $vrf_name"

    # Assign vrf_log_msg
    vrf_log_msg="in $vrf_name VRF"
fi

LOCKFILE=/run/lock/ntpdate

RUNASUSER=ntp
UGID=$(getent passwd $RUNASUSER | cut -f 3,4 -d:) || true
if test "$(uname -s)" = "Linux"; then
        NTPD_OPTS="$NTPD_OPTS -u $UGID"
fi

case $1 in
	start)
		log_daemon_msg "Starting NTP server $vrf_log_msg" "ntpd"
		if [ -z "$UGID" ]; then
			log_failure_msg "user \"$RUNASUSER\" does not exist"
			exit 1
		fi
		(
			flock -w 180 9

			$VRF start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE $NTPD_OPTS
		) 9>$LOCKFILE
		log_end_msg $?
  		;;
	stop)
		log_daemon_msg "Stopping NTP server" "ntpd"
		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --retry=TERM/30/KILL/5 --exec $DAEMON
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "NTP server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
