#! /bin/sh

### BEGIN INIT INFO
# Provides:          fetch-crl-boot
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     
# Default-Stop:      0 1 2 3 4 5 6
# Short-Description: Run fetch-crl on boot
# Description:       This shell script enables a run of fetch-crl on boot
### END INIT INFO

# Author: Mattias Ellert <mattias.ellert@physics.uu.se>

# source function library
. /lib/lsb/init-functions

# source any environment settings, e.g. for HTTP proxies
[ -f /etc/default/fetch-crl ] && . /etc/default/fetch-crl

lockfile=/var/lock/fetch-crl-boot

RETVAL=0

start() {
    log_begin_msg "Running fetch-crl on boot can take a while:"
    /usr/sbin/fetch-crl -q $FETCHCRL_OPTIONS $FETCHCRL_BOOT_OPTIONS
    RETVAL=$?
    if [ $RETVAL -eq 0 ] ; then
	touch $lockfile
	log_success_msg
    else
	log_failure_msg
    fi
}

stop() {
    RETVAL=0
    rm -f $lockfile
}

restart() {
    stop
    start
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|force-reload)
	restart
	;;
    condrestart)
	[ -f $lockfile ] && restart
	;;
    reload)
	;;
    status)
	if [ -f $lockfile ] ; then
	    log_success_msg "fetch-crl-boot lockfile present"
	    RETVAL=0
	else
	    log_success_msg "fetch-crl-boot lockfile not-present"
	    RETVAL=3
	fi
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
	RETVAL=1
esac

exit $RETVAL
