! template: common/daemons.common.conf.j2
!
hostname sonic
password zebra
enable password zebra
!
log syslog informational
log facility local4
!!
!
! end of template: common/daemons.common.conf.j2
!
! template: pimd.conf.db.route_map.j2
!
! end of template: pimd.conf.db.route_map.j2
!

