#!/bin/bash
# This script load/unload opennsl kernel modules

### BEGIN INIT INFO
# Provides:          load-opennsl-modules
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Load OpenNSL kernel modules
### END INIT INFO

KNET_BASEDEV_NAME=bcm0
KNET_CPUDEV_NAME=CPU
PTP_SUPPORTED_PLT=`lspci | grep Broadcom | grep -e 'b87'`
PTP_CONFIG_FILE="/usr/share/sonic/platform/ptp.json"
PTP_FEATURE_CONFIG_FILE="/etc/sonic/proprietary_feature.json"

function create_devices()
{
    if [ $is_ltsw_chip -eq 1 ]; then
       rm -f /dev/linux_ngbde
       rm -f /dev/linux_ngknet
       rm -f /dev/linux_ngknetcb
       rm -r /dev/linux-knet-pcap-rx
       rm -r /dev/linux-knet-pcap-tx
       rm -r /dev/linux-knet-pcap-drop

       mknod /dev/linux_ngbde    c 120 0
       mknod /dev/linux_ngknet   c 121 0
       mknod /dev/linux_ngknetcb  c 122 0
       mknod /dev/linux-knet-pcap-rx   c 280 0
       mknod /dev/linux-knet-pcap-tx   c 281 0
       mknod /dev/linux-knet-pcap-drop   c 282 0

    else
       rm -f /dev/linux-knet-cb
       rm -f /dev/linux-bcm-knet
       rm -f /dev/linux-bcm-bde
       rm -f /dev/linux-kernel-bde
       rm -r /dev/linux-knet-pcap-rx
       rm -r /dev/linux-knet-pcap-tx
       rm -r /dev/linux-knet-pcap-drop

       mknod /dev/linux-knet-cb    c 121 0
       mknod /dev/linux-bcm-knet   c 122 0
       mknod /dev/linux-bcm-bde    c 126 0
       mknod /dev/linux-kernel-bde c 127 0
       mknod /dev/linux-knet-pcap-rx   c 280 0
       mknod /dev/linux-knet-pcap-tx   c 281 0
       mknod /dev/linux-knet-pcap-drop   c 282 0
    fi
}

# linux-kernel-bde debug=4      ==> Verbose level debug
#              dma_debug=1      ==> Enable DMA debug
# linux-bcm-knet debug=0x201000 ==> Enable KNET Warning      (0x001000)
#                                   Enable KNET Pkt drop     (0x200000)
function load_kernel_modules()
{
    onie_platfrom=`grep onie_platform /host/machine.conf`
    export $onie_platfrom

    KBDE_USEMSI=0
    if [ -f /usr/share/sonic/device/$onie_platform/opennsl-modules.conf ]; then
        source /usr/share/sonic/device/$onie_platform/opennsl-modules.conf
    fi

    # Rx rate in PPS
    KNETRX_RATE=30000
    PLATFORM_COPP_RX_RATE_CONFIG=/etc/sonic/copp_rx_rate
    if [ -f $PLATFORM_COPP_RX_RATE_CONFIG ]; then
        rate=$(<$PLATFORM_COPP_RX_RATE_CONFIG)
        if [[ $rate =~ ^[0-9]+$ ]]; then
            if (( $rate >= 100 && $rate <= 100000 )); then
                KNETRX_RATE=$rate
            fi
        fi
    fi

    KNET_CPUDEV_PARAM="cpu_dev_name=$KNET_CPUDEV_NAME"
    if [ $is_ltsw_chip -eq 1 ]; then
      modprobe linux_ngbde dma_alloc="pgmem"
      modprobe linux_ngknet rx_buffer_size=9238 page_buffer_mode=0 txq_nb_desc=1024 debug=0x1800 # link changes and pkt drops
      modprobe psample
      modprobe linux_ngknetcb
      modprobe genl_packet
      modprobe linux_bcmgenl
      if [ -f $PTP_CONFIG_FILE ] && [ -f $PTP_FEATURE_CONFIG_FILE ]; then
          modprobe linux_ngptp_tspps
          modprobe linux_ngptp_clock
      fi

    else
      modprobe linux-kernel-bde usemsi=$KBDE_USEMSI dmasize=32M maxpayload=128 debug=4 dma_debug=1
      modprobe linux-user-bde
      modprobe linux-bcm-knet use_rx_skb=1 rx_buffer_size=9238 debug=0x201000 use_napi=1 base_dev_name=$KNET_BASEDEV_NAME rx_rate=$KNETRX_RATE,$KNETRX_RATE,$KNETRX_RATE,$KNETRX_RATE,$KNETRX_RATE,$KNETRX_RATE,$KNETRX_RATE rx_drop_threshold=7000 rx_resume_threshold=5000 rx_drop_qs_enable=0x4FFFFF max_tx_dcbs=1024 $KNET_CPUDEV_PARAM
      modprobe psample

      if [ -f $PTP_CONFIG_FILE ] && [ -f $PTP_FEATURE_CONFIG_FILE ]; then
          modprobe linux-ptp-tspps
          modprobe linux-ptp-clock
      else
          if [ ! -z "$PTP_SUPPORTED_PLT" ]; then
              modprobe linux-bcm-ptp-clock
          fi
      fi

      modprobe linux-knet-cb
      modprobe genl_packet
      modprobe linux_bcm_genl

      # Bring up knet basedev to enable NAPI
      while [[ -z $(ip link show $KNET_BASEDEV_NAME) ]]; do
          echo "Waiting for knet basedevice $KNET_BASEDEV_NAME ..."
          sleep 1
      done
      ip link set dev $KNET_BASEDEV_NAME up
    fi
}

function remove_kernel_modules()
{
    if [ -f /usr/share/sonic/device/$onie_platform/opennsl-modules.conf ]; then
        source /usr/share/sonic/device/$onie_platform/opennsl-modules.conf
    fi

    # Disable NAPI
    if [[ -z $(ip link show $KNET_BASEDEV_NAME) ]]
    then
        ip link set dev $KNET_BASEDEV_NAME down
        sleep 5
    fi

    if [[ $is_ltsw_chip -eq 1 ]]; then
        rmmod linux_bcmgenl
        rmmod genl_packet
        rmmod linux_ngknetcb
        rmmod psample
        rmmod linux_ngknet
        rmmod linux_ngbde
        if [ -f $PTP_CONFIG_FILE ] && [ -f $PTP_FEATURE_CONFIG_FILE ]; then
            rmmod linux_ngptp_clock
            rmmod linux_ngptp_tspps
        fi
    else
        if [ -f $PTP_CONFIG_FILE ] && [ -f $PTP_FEATURE_CONFIG_FILE ]; then
            rmmod linux-ptp-clock
            rmmod linux-ptp-tspps
        else
            if [ ! -z "$PTP_SUPPORTED_PLT" ]; then
                rmmod linux-bcm-ptp-clock
            fi
        fi

        rmmod linux_bcm_genl
        rmmod genl_packet
        rmmod linux-knet-cb
        sleep 1
        rmmod psample
        rmmod linux-bcm-knet
        rmmod linux-user-bde
        rmmod linux-kernel-bde
    fi
}

function load_platform_env()
{
    . /host/machine.conf

    if [ -n "$aboot_platform" ]; then
        platform=$aboot_platform
    elif [ -n "$onie_platform" ]; then
        platform=$onie_platform
    else
        platform="unknown"
    fi

    # Set the default configuration for s_ltsw_chip parameter
    is_ltsw_chip=0

    # Source the platform env file
    env_file="/usr/share/sonic/device/$platform/platform_env.conf"
    source $env_file
}

case "$1" in
start)
    echo -n "Load OpenNSL kernel modules... "

    load_platform_env
    create_devices
    load_kernel_modules

    echo "done."
    ;;

stop)
    echo -n "Unload OpenNSL kernel modules... "

    load_platform_env
    remove_kernel_modules

    echo "done."
    ;;

force-reload|restart)
    echo "Not supported"
    ;;

*)
    echo "Usage: /etc/init.d/opennsl-modules.init {start|stop}"
    exit 1
    ;;
esac

exit 0

