onie_arch=x86_64
onie_bin=
onie_boot_fs_type=ext4
onie_boot_gfdisk_type=0x3000
onie_boot_gpt_uuid=7412F7D5-A156-4B13-81DC-867174929325
onie_boot_label=ONIE-BOOT
onie_boot_mnt=/mnt/onie-boot
onie_boot_reason=install
onie_build_date=2023-04-17T20:09-07:00
onie_build_machine=dellemc_s5200_c3538
onie_build_platform=x86_64-dellemc_s5200_c3538-r0
onie_cli_static_parms=
onie_cli_static_url=http://10.170.252.143/cisco/Enterprise_SONiC_OS_4.5.0_Enterprise_Standard.bin
onie_config_dir=/mnt/onie-boot/onie/config
onie_config_version=1
onie_default_filename=onie-installer-x86_64-dellemc_s5248f_c3538-r0
onie_default_filenames=onie-installer-x86_64-dellemc_s5248f_c3538-r0
onie_dev=/dev/sda2
onie_exec_url=http://10.170.252.143/cisco/Enterprise_SONiC_OS_4.5.0_Enterprise_Standard.bin
onie_firmware=auto
onie_grub_image_name=grubx64.efi
onie_iana_enterprise=42623
onie_image_suffixes=.bin
onie_image_type_nos=nos
onie_image_type_update=update
onie_initrd_tmp=/
onie_installer=/var/tmp/installer
onie_kernel_version=4.9.30
onie_machine=dellemc_s5248f_c3538
onie_machine_rev=0
onie_operation=os-install
onie_partition_type=gpt
onie_platform=x86_64-dellemc_s5248f_c3538-r0
onie_root_dir=/mnt/onie-boot/onie
onie_server_name=onie-server
onie_skip_ethmgmt_macs=no
onie_switch_asic=bcm
onie_uefi_arch=x64
onie_uefi_boot_loader=grubx64.efi
onie_update_attempts_dir=/mnt/onie-boot/onie/update/attempts
onie_update_dir=/mnt/onie-boot/onie/update
onie_update_log=/mnt/onie-boot/onie/update/update.log
onie_update_pending_dir=/mnt/onie-boot/onie/update/pending
onie_update_preserve_update_dir=/mnt/onie-boot/onie/update/preserve-update
onie_update_results_dir=/mnt/onie-boot/onie/update/results
onie_updater_cookie=ONIE-UPDATER-COOKIE
onie_vendor_id=674
onie_version=3.40.1.1-9
