configure ports eth0 lldp portidsubtype local eth0
configure system ip management pattern 10.92.56.60
configure system hostname MYBLE01-DC-0409-SI02
pause
configure system description "SONiC Software Version: SONiC.4.5.1-Enterprise_Standard - HwSku: DellEMC-S5248f-P-25G-DPB - Distribution: Debian 11.11 - Kernel: 5.10.0-35-amd64"
