#!/bin/sh

if [ "$(sonic-db-cli STATE_DB PING)" = "True" ]; then
    disk_name="$(lsblk -ndo pkname ${UM_DEVICE})"
    FSTYPE=$(lsblk -no KNAME,FSTYPE ${UM_DEVICE} | head -1 | awk '{print $2}')
    if [ "${FORCE}" = "y" ]; then
        eval $(udevadm info --query=env --export "${UM_DEVICE}" | grep -v '^[^=]*\..*=')
        vendor=
        if [ -r "/sys$DEVPATH/device/vendor" ]; then
            vendor="`cat \"/sys$DEVPATH/device/vendor\"`"
        elif [ -r "/sys$DEVPATH/../device/vendor" ]; then
            vendor="`cat \"/sys$DEVPATH/../device/vendor\"`"
        elif [ -r "/sys$DEVPATH/device/../manufacturer" ]; then
            vendor="`cat \"/sys$DEVPATH/device/../manufacturer\"`"
        elif [ -r "/sys$DEVPATH/../device/../manufacturer" ]; then
            vendor="`cat \"/sys$DEVPATH/../device/../manufacturer\"`"
        fi
        vendor="$(echo "$vendor" | sed 's/^[[:blank:]]\+//; s/[[:blank:]]\+$//')"

        model=
        if [ -r "/sys$DEVPATH/device/model" ]; then
            model="`cat \"/sys$DEVPATH/device/model\"`"
        elif [ -r "/sys$DEVPATH/../device/model" ]; then
            model="`cat \"/sys$DEVPATH/../device/model\"`"
        elif [ -r "/sys$DEVPATH/device/../product" ]; then
            model="`cat \"/sys$DEVPATH/device/../product\"`"
        elif [ -r "/sys$DEVPATH/../device/../product" ]; then
            model="`cat \"/sys$DEVPATH/../device/../product\"`"
        fi
        model="$(echo "$model" | sed 's/^[[:blank:]]\+//; s/[[:blank:]]\+$//')"
    else
        vendor="${UM_VENDOR}"
        model="${UM_MODEL}"
        
    fi

    if [ -z $disk_name ]; then
        sonic-db-cli STATE_DB HSET "USB_DEVICE|${UM_DEVICE}" model_name "${model}" manufacturer "${vendor}" > /dev/null
        if [ "${FSTYPE}" != "" ]; then
            sonic-db-cli STATE_DB HSET "USB_PARTS|${UM_DEVICE}" usb_device "${UM_DEVICE}" filesystem "${FSTYPE}" mount_point "" > /dev/null
        fi
    else
        sonic-db-cli STATE_DB HSET "USB_PARTS|${UM_DEVICE}" usb_device "/dev/${disk_name}" filesystem "${FSTYPE}" mount_point "" > /dev/null
    fi
fi
