#Rule to store the audit logs in file /var/log/audit.log
if $msg contains '[audit]' then {
    *.* action(type="omfile" file="/var/log/audit.log" template="SONiCFileFormat")
    set $/slogcnt = $/slogcnt + 1;
    stop
}
