#IPv6 duplicate address message from kernel
if ($syslogfacility-text == 'kern' and $msg contains "IPv6 duplicate address") then {
    /var/log/syslog
}

if ($/slogcnt > 30000) then {
	# Trigger the log rotation for every 30k messsage(>~5MB)
	*.* /var/log/rotate/disk/syslog
	set $/slogcnt = 0;
}

if $programname contains "clish" then {
    /var/log/clish.log
    set $/slogcnt = $/slogcnt + 1;
    stop
}

if ($msg contains "msg=audit") then {
    stop
}

## rsyslog omfwd failure logs
if $programname contains "rsyslogd" then {
    if ($msg contains "omfwd") then {
        /var/log/rsyslogd_omfwd.log
        set $/slogcnt = $/slogcnt + 1;
        stop
    }
    if ($msg contains "HUPed" or $msg contains "reloaded from file") then {
        stop
    }
}

# In-Memory syslog configurations
$IncludeConfig /etc/rsyslog.d/in-memory/*.conf


if ($msg contains "lua") then {
    /var/log/lua_redis.log
    stop
}
## Quagga rules

if re_match($programname, "bgp[0-9]*#(zebra|staticd|watchfrr)") then {
    /var/log/frr/frr.log
    stop
}

if $programname contains "bgp[0-9]*#bgpd" then {
    if not ($msg contains "ADJCHANGE: neighbor") then {
        /var/log/frr/frr.log
        stop
    }
}

## Teamd rules

if $programname contains "teamd_" then {
    /var/log/teamd.log
    stop
}

## fdbsyncd rules
if $programname contains "swss#fdbsyncd" then {
    if not ($msg contains "FDBSYNCD_SYSLOG") then {
        /var/log/fdbsync.log
        stop
    }
}

## STPd rules
if $programname contains "stp" then {
    if not ($msg contains "STP_SYSLOG") then {
        /var/log/stpd.log
        stop
    }
}

## LLDP rules
if $programname contains "lldp" then {
    /var/log/lldp.log
    stop
}

## UDLDd rules
if $programname contains "udld" then {
    if not ($msg contains "UDLD_SYSLOG") then {
        /var/log/udldd.log
        stop
    }
}

## Neighsyncd rules
if $programname contains "neighsyncd" then {
    if ($syslogseverity >= 5) then {
        /var/log/neighsyncd.log
        stop
    }
}

## NbrMgrd rules
if $programname contains "nbrmgrd" then {
    if ($syslogseverity >= 5) then {
        if not ($msg contains "NBRMGRD_SYSLOG") then {
            /var/log/nbrmgrd.log
            stop
        }
    }
}



## ICCPd rules
#
if $programname contains "iccp" then {
    if ($msg contains "ICCP_FSM") then {
        /var/log/iccp/iccpd.log
        stop
    }
    if ($msg contains "ICCP_FDB") then {
        /var/log/iccp/iccpd_fdb.log
        stop
    }
    if ($msg contains "ICCP_NETLINK") then {
        /var/log/iccp/iccpd_netlink.log
        stop
    }
    if ($msg contains "ICCP_NEIGH") then {
        /var/log/iccp/iccpd_neigh.log
        stop
    }
    if ($msg contains "ICCP_L2MC") then {
        /var/log/iccp/iccpd_l2mc.log
        stop
    }
}

## fdborch rules
if $programname contains "orchagent" then {
    if ($msg contains "fdbEvent") then {
        /var/log/fdb_orch_syncd.log
        stop
    }
}

## syncd fdb rules
if $programname contains "syncd" then {
    if ($msg contains "fdbEvent") then {
        /var/log/fdb_orch_syncd.log
        stop
    }
}


## dhclient log rules
if $programname == 'dhclient' then {
    if $msg contains "XMT: Solicit on " then {
        stop
    }
}

#snmpd logs with LOCAL4 facility
if $syslogfacility-text == 'local4' then {
    if $programname contains "snmpd" then {
		if ($syslogseverity > 6) then {
			/var/log/snmpd_debug.log
			stop	
		}
	}
}
