

# General debug log rules
# This rules enforce the log file rotation automatically when its size crosses 10K messages (or) 5MB
if ($syslogseverity >= 6) then {

	
	if ($syslogseverity == 6) then {

		# enable auto rotate when log file size exceed 5MB
		$outchannel in_memory_info_log_rotation,/var/log/ramfs/in-memory-syslog-info.log, \
			5242880,/usr/bin/rotate_limit.sh info
		*.* :omfile:$in_memory_info_log_rotation
		
        if ($/infocnt > 10000) then {
				# Trigger the log rotation for every 10k messsage(>~2MB)
                *.* /var/log/rotate/in-memory/info
                set $/infocnt = 0;
        } else {
                set $/infocnt = $/infocnt + 1;
        }

		stop
	}
	if ($syslogseverity == 7) then {

		# enable auto rotate when log file size exceed 5MB
		$outchannel in_memory_debug_log_rotation,/var/log/ramfs/in-memory-syslog-debug.log, \
			5242880,/usr/bin/rotate_limit.sh debug
		*.* :omfile:$in_memory_debug_log_rotation

        if ($/dbgcnt > 10000) then {
				# Trigger the log rotation for every 10k messsage(>~2MB)
                *.* /var/log/rotate/in-memory/debug
                set $/dbgcnt = 0;
        } else {
                set $/dbgcnt = $/dbgcnt + 1;
        }

		stop
	}
}else{
	if ($/slogcnt > 30000) then {
			# Trigger the log rotation for every 30k messsage(>~5MB)
			*.* /var/log/rotate/disk/syslog
			set $/slogcnt = 0;
	} else {
			set $/slogcnt = $/slogcnt + 1;
	}


}

